### ISSUE TITLE
Metaio SDK问题请教

### ISSUE THREAD

**Issue by JhPocket** [skytoup/LocationARTest#2]
你好，同学，我是国内高校的一名学生，正在做AR相关的应用，请问现在Metaio SDK是不能获得了吗

**Comment by skytoup** [comment]
是的

**Comment by JhPocket** [comment]
谢谢

**Comment by skytoup** [comment]
不知道哪里有issue的提醒，今天才看到😥

**Comment by JhPocket** [comment]
我是邮件通知才看到的，问题解决了，学习了[ProAndroidAugmentedReality](https://github.com/RaghavSood/ProAndroidAugmentedReality)其中的例子

**Comment by skytoup** [comment]
好吧，可能当时比较少看邮件
